[package]
name = "rusty_scrap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.4"
select = "0.5.0"
tokio = {version = "1.12.0", features = ["full"]}
error_chain = "0.12.4"
